- hosts: all
  remote_user: ubuntu
  gather_facts: false
  become: true 
  serial:
    - "50%"
  vars:
    ansible_port: 22
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /home/grey/Desktop/demo.pem
  tasks:
  - name: Install apache
    apt:
      name: apache2
      state: latest
  - name: Remove apache
    apt: 
      name: apache2
      state: absent