- hosts: localhost
  vars:
    vault_token: 
    vault_url: 'http://127.0.0.1:8200'
    db_password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/passwords/db token={{ vault_token }} url={{ vault_url }}') }}"
    system_password: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/passwords/system token={{ vault_token }} url={{ vault_url }}') }}"
  tasks:
  - name: Value For db_password
    debug:
      msg: "db_password: {{ db_password }}"
  - name: Value For system_password
    debug:
      msg: "db_password: {{ system_password }}" 