- hosts: localhost
  tasks:
    - name: Return all secrets from a path
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.hashi_vault', 'secret=secret/data/passwords/db token=hvs.S7Py8a4S4ZH1DV8Wu5Cxezd5 url=http://localhost:8200') }}"