- hosts: web
  remote_user: root
  become: yes
  vars:
    packages:
      - apache2
      - docker
      - mysql-server
  tasks:
  - name: Install Software
    apt:
      name: "{{ item }}"
      state: present
    loop: "{{ packages }}"
  - name: Remove Software
    apt: 
      name: 
        - apache2
        - docker
        - mysql-server
      state: absent