- hosts: web
  remote_user: root
  become: true
  tasks:
  - name: Update apt
    apt:
      update_cache: yes
  - name: Install Apache
    apt:
      name: apache2
      state: present
    notify: 
      - Restart Apache
  - name: Install mysql
    apt:
      name: mysql-server
      state: present
    notify: 
      - Restart Apache
  - name: Install php
    apt:
      name: php
      state: present
    notify: 
      - Restart Apache
  - name: Remove Packages
    apt: 
      name:
        - apache2
        - mysql-server
        - php
      state: absent
  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
    