- hosts: web
  remote_user: root
  become: true
  tasks:
  - name: Install Apache
    apt:
      name: apache2
      state: present
  - name: Restart Apache
    service:
      name: apache2
      state: restarted
  - name: Remove Apache
    apt: 
      name: apache2
      state: absent